"""empty message

Revision ID: 210a0b4adb35
Revises: 
Create Date: 2021-04-29 12:18:15.756000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '210a0b4adb35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'movies', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
